CREATE DATABASE IF NOT EXISTS ci;

USE ci;

DROP TABLE IF EXISTS exoplanets;
DROP TABLE IF EXISTS solar_flares;

-- Code added by Charan 

DROP TABLE IF EXISTS stars;
DROP TABLE IF EXISTS asteriods;

-- End

CREATE TABLE exoplanets (
    pl_name VARCHAR(255) NOT NULL,
    hostname VARCHAR(255) NOT NULL,
    default_flag TINYINT,
    sy_snum INT,
    sy_pnum INT,
    discoverymethod VARCHAR(255),
    disc_year INT, -- YEAR datatype starts at 1900
    disc_facility VARCHAR(255),
    soltype VARCHAR(255),
    pl_controv_flag TINYINT,
    pl_refname VARCHAR(240),
    pl_orbper FLOAT,
    pl_orbpererr1 FLOAT,
    pl_orbpererr2 FLOAT,
    pl_orbperlim TINYINT,
    pl_orbsmax FLOAT,
    pl_orbsmaxerr1 FLOAT,
    pl_orbsmaxerr2 FLOAT,
    pl_orbsmaxlim TINYINT,
    pl_rade FLOAT,
    pl_radeerr1 FLOAT,
    pl_radeerr2 FLOAT,
    pl_radelim TINYINT,
    pl_radj FLOAT,
    pl_radjerr1 FLOAT,
    pl_radjerr2 FLOAT,
    pl_radjlim TINYINT,
    pl_bmasse FLOAT,
    pl_bmasseerr1 FLOAT,
    pl_bmasseerr2 FLOAT,
    pl_bmasselim TINYINT,
    pl_bmassj FLOAT,
    pl_bmassjerr1 FLOAT,
    pl_bmassjerr2 FLOAT,
    pl_bmassjlim TINYINT,
    pl_bmassprov VARCHAR(255),
    pl_orbeccen FLOAT,
    pl_orbeccenerr1 FLOAT,
    pl_orbeccenerr2 FLOAT,
    pl_orbeccenlim TINYINT,
    pl_insol FLOAT,
    pl_insolerr1 FLOAT,
    pl_insolerr2 FLOAT,
    pl_insollim TINYINT,
    pl_eqt FLOAT,
    pl_eqterr1 FLOAT,
    pl_eqterr2 FLOAT,
    pl_eqtlim TINYINT,
    ttv_flag TINYINT,
    st_refname TEXT,
    st_spectype VARCHAR(50),
    st_teff FLOAT,
    st_tefferr1 FLOAT,
    st_tefferr2 FLOAT,
    st_tefflim TINYINT,
    st_rad FLOAT,
    st_raderr1 FLOAT,
    st_raderr2 FLOAT,
    st_radlim TINYINT,
    st_mass FLOAT,
    st_masserr1 FLOAT,
    st_masserr2 FLOAT,
    st_masslim TINYINT,
    st_met FLOAT,
    st_meterr1 FLOAT,
    st_meterr2 FLOAT,
    st_metlim TINYINT,
    st_metratio VARCHAR(10),
    st_logg FLOAT,
    st_loggerr1 FLOAT,
    st_loggerr2 FLOAT,
    st_logglim TINYINT,
    sy_refname TEXT,
    rastr VARCHAR(20),
    ra FLOAT,
    decstr VARCHAR(20),
    declination FLOAT, -- "dec" conflicts with mysql type
    sy_dist FLOAT,
    sy_disterr1 FLOAT,
    sy_disterr2 FLOAT,
    sy_vmag FLOAT,
    sy_vmagerr1 FLOAT,
    sy_vmagerr2 FLOAT,
    sy_kmag FLOAT,
    sy_kmagerr1 FLOAT,
    sy_kmagerr2 FLOAT,
    sy_gaiamag FLOAT,
    sy_gaiamagerr1 FLOAT,
    sy_gaiamagerr2 FLOAT,
    rowupdate VARCHAR(255), -- making dates VARCHAR because many are malformed
    pl_pubdate VARCHAR(255),
    releasedate VARCHAR(255),
    PRIMARY KEY(pl_name, hostname, pl_refname));

CREATE TABLE solar_flares(
    flare_id VARCHAR(200),
    start_time DATETIME,
    peak_time DATETIME,
    end_time DATETIME,
    class_type VARCHAR(20),
    source_location VARCHAR(20),
    active_region VARCHAR(20),
    linked_events VARCHAR(1000),
    instruments VARCHAR(200),
    note VARCHAR(1000),
    PRIMARY KEY(flare_id)
);


-- Code added by Charan
CREATE TABLE asteroids (
    orbit_id INT,
    orbit_determination_date VARCHAR(255),
    first_observation_date DATE,
    last_observation_date DATE,
    data_arc_in_days INT,
    observations_used INT,
    orbit_uncertainty INT,
    minimum_orbit_intersection FLOAT,
    jupiter_tisserand_invariant FLOAT,
    epoch_osculation FLOAT,
    eccentricity FLOAT,
    semi_major_axis FLOAT,
    inclination FLOAT,
    ascending_node_longitude FLOAT,
    orbital_period FLOAT,
    perihelion_distance FLOAT,
    perihelion_argument FLOAT,
    aphelion_distance FLOAT,
    perihelion_time FLOAT,
    mean_anomaly FLOAT,
    mean_motion FLOAT,
    equinox VARCHAR(255),
    orbit_class VARCHAR(255),
    id INT,
    PRIMARY KEY(id)
);

CREATE TABLE stars (
    sy_name VARCHAR(255),
    hostname VARCHAR(255),
    tic_id VARCHAR(255),
    sy_snum INT,
    sy_pnum INT,
    st_refname VARCHAR(255),
    st_spectype VARCHAR(255),
    st_teff FLOAT,
    st_tefferr1 FLOAT,
    st_tefferr2 FLOAT,
    st_tefflim TINYINT,
    st_rad FLOAT,
    st_raderr1 FLOAT,
    st_raderr2 FLOAT,
    st_radlim TINYINT,
    st_mass FLOAT,
    st_masserr1 FLOAT,
    st_masserr2 FLOAT,
    st_masslim TINYINT,
    st_met FLOAT,
    st_meterr1 FLOAT,
    st_meterr2 FLOAT,
    st_metlim TINYINT,
    st_metratio VARCHAR(255),
    st_logg FLOAT,
    st_loggerr1 FLOAT,
    st_loggerr2 FLOAT,
    st_logglim TINYINT,
    sy_refname VARCHAR(255),
    rastr VARCHAR(255),
    ra FLOAT,
    decstr VARCHAR(255),
    decliniation FLOAT,
    sy_dist FLOAT,
    sy_disterr1 FLOAT,
    sy_disterr2 FLOAT,
    sy_vmag FLOAT,
    sy_vmagerr1 FLOAT,
    sy_vmagerr2 FLOAT,
    sy_kmag FLOAT,
    sy_kmagerr1 FLOAT,
    sy_kmagerr2 FLOAT,
    sy_gaiamag FLOAT,
    sy_gaiamagerr1 FLOAT,
    sy_gaiamagerr2 FLOAT,
    PRIMARY KEY(sy_name, hostname, st_refname)
);
-- End
